### PR TITLE
update deps, vendor go/printer from Go 1.19

### LINKED ISSUE #244: gofumpt's behaviour depends on the version of Go used to build it
I'm finding that the behaviour of `gofumpt` is sensitive to the version of Go used to build the binary. It also looks to not fully respect the `-lang` flag _(ed.: this was a misreading on my part; see the discussion below)_. A reproducing example follows.

This was first raised [here](https://github.com/golangci/golangci-lint/issues/3175); I misattributed things.

(I'll try and fix the problem rather than only whinge like an ingrate, but I think it's a good idea to raise the issue here first.)

# Reproducing example

## Preparing

Prepare an empty directory with the following files:

```go
// main.go
package main

// Hello, world.
//
// - This will be modified by `gofumpt` if the version of Go is 1.19, but not
//   if the version is 1.18.
func main() {
}
```

```yaml
# docker-compose.yml
services:
  gofumpt18:
    image: golang:1.18-bullseye
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/

  gofumpt19:
    image: golang:1.19-bullseye
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/
```

Then run:

```sh
docker compose up -d
```

## Installing via `go install`

```sh
docker compose exec gofumpt18 bash

go install mvdan.cc/gofumpt@latest
cd /go/src
gofumpt -d main.go # No differences.
gofumpt -lang "1.19" -d main.go # No differences.
gofumpt -lang "1.18" -d main.go # No differences.
exit
```

```sh
docker compose exec gofumpt19 bash

go install mvdan.cc/gofumpt@latest
cd /go/src
gofumpt -d main.go # Differences.
gofumpt -lang "1.19" -d main.go # Differences.
gofumpt -lang "1.18" -d main.go # Differences.
exit
```

## Building with Go 1.18, running in a Go 1.19 context

```sh
docker compose exec gofumpt18 bash

cp $(which gofumpt) /go/src
exit
```

```sh
docker compose exec gofumpt19 bash

cd /go/src
./gofumpt -d main.go # No differences.
./gofumpt -lang "1.19" -d main.go # No differences.
./gofumpt -lang "1.18" -d main.go # No differences.
exit
```

## Building with Go 1.19, running in a Go 1.18 context

```sh
docker compose exec gofumpt19 bash

cp $(which gofumpt) /go/src
exit
```

```sh
docker compose exec gofumpt18 bash

cd /go/src
./gofumpt -d main.go # Differences.
./gofumpt -lang "1.19" -d main.go # Differences.
./gofumpt -lang "1.18" -d main.go # Differences.
exit
```

## Cleaning up

```sh
docker compose down
```

### PR DESCRIPTION
**Pull request by mvdan**
(see commit messages - please do not squash)

Fixes #244.

### CODE REVIEW

**Comment by mvdan** [comment]
cc @adamroyjones, would love your review as well :)

**Comment by mvdan** [comment]
also cc @findleyr to hear whether this would be good or bad news for gopls.

**Review by Oiyoo — APPROVED** [review]

**Review by adamroyjones — COMMENTED** [review]
I'm sorry it's taken me so long to have a look. It all looks sensible—thanks for making these changes (and for writing such a rich commit message).

Do you think a new version of gofumpt ought to be tagged?

**Comment by mvdan** [comment]
Yes, soon. I want to check with the gopls people first, to see if this sort of vendoring will be a problem for them.

**Pull request merged**
