### PR TITLE
WIP fix: restore CGO compatibility

### LINKED ISSUE #86: breaking CGO compabitility
Hi,

I've this go file:

```go
// +build darwin

package mcdriver

/*
#cgo CFLAGS: -x objective-c
#cgo darwin LDFLAGS: -framework Foundation -framework MultipeerConnectivity
#include <stdlib.h>
#include "mc-driver.h"
*/
import "C"
import "unsafe"

[...]
```

Becoming like this (after running `go run mvdan.cc/gofumpt -w -s .`)

```go
// +build darwin

package mcdriver

/*
#cgo CFLAGS: -x objective-c
#cgo darwin LDFLAGS: -framework Foundation -framework MultipeerConnectivity
#include <stdlib.h>
#include "mc-driver.h"
*/
import (
        "C"
        "unsafe"
)

[...]
```

Which breaks the requirements needed to use CGO: https://golang.org/cmd/cgo/#hdr-Using_cgo_with_the_go_command

---

I don't have the necessary knowledge to make a PR for this, sorry, but I would like to know if someone can help supporting CGO files?

Else, it would be nice to have a way of defining files to exclude, i.e. by detecting this `import "C"`, or manually by specifying an exclude list?

Thank you very much

### PR DESCRIPTION
**Pull request by moul**
fixes #86

### CODE REVIEW

**Comment by moul** [comment]
I added some unit tests first, then I tried various simple things: continue and fallthrough on "C", but no luck

I continue to investigate how the codebase works

I'm really sorry, but can you help me a little bit more?

**Comment by mvdan** [comment]
Perhaps try using debug prints with `go test -run Script/std-imports` to see what's going on. I can help later today if you're still wanting help.

**Comment by moul** [comment]
that's what I was doing, but thx for the hint :)

my last commit seems to increase compatibility but not totally

**Comment by mvdan** [comment]
Your golden file also separates the C import with an empty line, which I assume we are not enforcing. You could insert that newline yourself near the end of the import, we have a func for it.

It might also be easiest to match `import "C"` before we call `joinStdImports`, so that we don't call the func at all.

**Comment by moul** [comment]
I tried to ignore joinStdImports in the case of `import "C"`, but `joinStdImports` is called in a condition that can never happen in that case, because `import "C"` isn't in a parenthesis group

**Pull request closed without merging**
